name: myfriends_app
description: "An emergency SOS app that instantly notifies your trusted contacts with your live location."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # Firebase Core 
  firebase_core: ^4.2.0
  
  # Firebase Services
  firebase_auth: ^6.1.1                    
  cloud_firestore: ^6.0.3                 
  firebase_storage: ^13.0.3                
  firebase_messaging: ^16.0.3             
  
  # State Management
  provider: ^6.1.2                       
  
  # Image Handling
  image_picker: ^1.1.2                     
  cached_network_image: ^3.4.1            
  image: ^4.2.0                           
  
  # Local Notifications (untuk FCM foreground)
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

  # Utilities
  intl: ^0.19.0                          
  url_launcher: ^6.3.1                     
  permission_handler: ^11.3.1             
  shared_preferences: ^2.3.3              
  smooth_page_indicator: ^1.2.0            
  geolocator: ^13.0.2                      
  
  # Export CSV
  csv: ^6.0.0                              
  path_provider: ^2.1.5                    
  share_plus: ^12.0.1
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

  # Custom Fonts - Poppins
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900